### ISSUE TITLE
'teasers_on_front' Argument Overwritten in Archive Template

### ISSUE THREAD

**Issue by clreed87** [billerickson/Genesis-Grid#16]
In a CPT archive template the `teasers_on_front` and `teasers_inside_arguments` aren't being applied to the loop and instead are using the arguments defined in the dashboard settings. 

The other arguments are passed into the grid loop without any issue. 

```
add_filter( 'genesis_grid_loop_args', 'enterprise_manufacturer_archive_grid_loop_args' );
function enterprise_manufacturer_archive_grid_loop_args( $args ) {

$args = array(
'features_on_front' => 0,
'teasers_on_front' => 9,
'features_inside' => 0,
'teasers_inside' => 9,
'teaser_columns' => 3,
);

return $args;	
}
```

**Comment by billerickson** [comment]
If you are changing the number of posts in the query, you need to place this code in functions.php. The query itself runs prior to the template loading. Here's a simplified load order:

- functions.php loads
- initial query arguments built
- pre_get_posts runs (allowing you to change query arguments)
- initial query runs
- based on query, template selected for display
- template loaded (ex: archive-cpt.php)
- loop displayed

If you place your filter in archive-cpt.php, it is running AFTER the initial query has run, so is not able to modify the query. It can only modify the loop (how the posts in the current query are displayed).

If you move your code to functions.php, it is loaded BEFORE the initial query and can modify that query.

**Comment by clreed87** [comment]
Thanks so much for the response. That was my problem--sorry for writing it as an issue instead of on the support forum.
